# Generated by Django 4.2 on 2026-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_resume_tailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='template_name',
            field=models.CharField(choices=[('modern_ats', 'Modern ATS'), ('corporate_ats', 'Corporate ATS')], max_length=50),
        ),
    ]
