# Generated by Django 4.2 on 2026-07-04 18:50
# Hand-edited: the local migration history (0001/0002) had drifted from the
# actual DB schema — Portfolio, Profile.resume_parsed, and the job/location
# indexes already exist physically but were untracked in migration state.
# SeparateDatabaseAndState updates Django's state to match reality without
# re-running DDL for things that already exist.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_generatedresume_html_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('ats', 'ATS Optimized')], default='ats', max_length=20)),
                ('content', models.JSONField()),
                ('ats_score', models.IntegerField(default=0)),
                ('ats_breakdown', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume_credits',
        ),
        migrations.DeleteModel(
            name='GeneratedResume',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Portfolio',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_public', models.BooleanField(default=False)),
                        ('template', models.CharField(choices=[('classic', 'Classic'), ('bento', 'Bento')], default='classic', max_length=20)),
                        ('theme', models.CharField(choices=[('minimal', 'Minimal'), ('noir', 'Noir'), ('noir-violet', 'Noir Violet'), ('minimal-violet', 'Minimal Violet'), ('noir-blue', 'Noir Blue'), ('minimal-blue', 'Minimal Blue')], default='noir', max_length=20)),
                        ('title', models.CharField(blank=True, max_length=100)),
                        ('bio', models.TextField(blank=True)),
                        ('github_url', models.URLField(blank=True, max_length=500)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.AddField(
                    model_name='profile',
                    name='resume_parsed',
                    field=models.JSONField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='job',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='location',
                    name='country',
                    field=models.CharField(db_index=True, max_length=100),
                ),
            ],
            database_operations=[],
        ),
    ]
