# Generated by Django 5.0.2 on 2026-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_resume_credits_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_parsed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
