# Generated by Django 5.0.2 on 2026-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_resume_parsed_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('noir', 'Noir')], default='noir', max_length=20),
        ),
    ]
