# Generated by Django 5.0.2 on 2026-07-02 09:55

from django.db import migrations


def backfill(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('api', 'Profile')
    Portfolio = apps.get_model('api', 'Portfolio')

    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)
    for user in User.objects.filter(portfolio__isnull=True):
        Portfolio.objects.create(user=user)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restore_job_and_location_indexes'),
    ]

    operations = [
        migrations.RunPython(backfill, noop_reverse),
    ]
