# Generated by Django 5.0.2 on 2026-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_backfill_missing_profiles_and_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('noir', 'Noir'), ('noir-violet', 'Noir Violet'), ('minimal-violet', 'Minimal Violet'), ('noir-blue', 'Noir Blue'), ('minimal-blue', 'Minimal Blue')], default='noir', max_length=20),
        ),
    ]
