# Generated by Django 5.0.2 on 2026-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_bento_theme_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('noir', 'Noir'), ('noir-violet', 'Noir Violet'), ('minimal-violet', 'Minimal Violet'), ('noir-blue', 'Noir Blue'), ('minimal-blue', 'Minimal Blue'), ('custom', 'Custom')], default='noir', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_accent',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='custom_dark',
            field=models.BooleanField(default=True),
        ),
    ]
