# Generated by Django 5.0.2 on 2026-07-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_google_id_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='custom_accent',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='custom_dark',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_id',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('noir', 'Noir'), ('noir-violet', 'Noir Violet'), ('minimal-violet', 'Minimal Violet'), ('noir-blue', 'Noir Blue'), ('minimal-blue', 'Minimal Blue')], default='noir', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('ats', 'ATS Optimized')], default='ats', max_length=20)),
                ('content', models.JSONField()),
                ('ats_score', models.IntegerField(default=0)),
                ('ats_breakdown', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('qa', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_kits', to='api.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_kits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
