# Generated by Django 5.0.2 on 2026-07-13 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_custom_cv_and_job_application_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(db_index=True, default='jobspy', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapesession',
            name='stage',
            field=models.CharField(db_index=True, default='discovery', max_length=20),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_normalized', models.CharField(db_index=True, max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('career_page_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('contact_page_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('discovered_via_site', models.CharField(blank=True, max_length=100, null=True)),
                ('discovery_source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('ats_platform', models.CharField(choices=[('unknown', 'Unknown'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('smartrecruiters', 'SmartRecruiters'), ('workday', 'Workday'), ('generic', 'Generic (no ATS detected)')], db_index=True, default='unknown', max_length=20)),
                ('ats_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('ats_api_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('resolution_attempts', models.IntegerField(default=0)),
                ('resolution_error', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_job_count', models.IntegerField(default=0)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['resolution_status', 'ats_platform'], name='api_company_resolut_6fb6e7_idx')],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.company'),
        ),
    ]
