# Generated by Django 5.0.2 on 2026-07-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_job_source_scrapesession_stage_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_ref',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.RemoveField(
            model_name='scrapesession',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
