# Generated by Django 5.0.2 on 2026-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_job_company_ref_remove_job_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
