# Generated by Django 5.0.2 on 2026-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_job_experience_required_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(db_index=True, default='Other', max_length=50),
        ),
    ]
