# Generated by Django 5.0.2 on 2026-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.CharField(max_length=500),
        ),
    ]
