# Generated by Django 5.0.2 on 2026-07-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_city_state_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
