# Generated by Django 5.0.2 on 2026-07-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_drop_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('career_url', models.URLField(max_length=1000)),
                ('contact_url', models.URLField(blank=True, max_length=1000)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
