# Generated by Django 5.0.2 on 2026-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='saved', max_length=20),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
