# Generated by Django 5.0.2 on 2026-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_portfolioview'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioview',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='country_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='device',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
