# Generated by Django 5.0.2 on 2026-07-17 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_portfolioview_browser_portfolioview_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('bento', 'Bento'), ('custom', 'Custom')], default='classic', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomPortfolioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('idea', models.TextField(blank=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_portfolio_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
