# Generated by Django 5.0.2 on 2026-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_portfolio_template_customportfoliotemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('bento', 'Bento')], default='classic', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomPortfolioTemplate',
        ),
    ]
