# Generated by Django 5.0.2 on 2026-07-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_scraped_at',
        ),
        migrations.DeleteModel(
            name='ScrapeLog',
        ),
        migrations.DeleteModel(
            name='ScrapeSession',
        ),
    ]
