# Generated by Django 5.0.2 on 2026-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_company_last_scraped_at_delete_scrapelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
