# Generated by Django 5.0.2 on 2026-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_company_last_scraped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='running', max_length=10)),
                ('triggered_by', models.CharField(choices=[('admin', 'Admin'), ('scheduler', 'Scheduler')], default='admin', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('geocoded', models.IntegerField(default=0)),
                ('borrowed', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
