# Generated by Django 5.0.2 on 2026-08-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0002_ambassadorprofile'),
        ('api', '0031_scraperrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='ambassador.ambassadorprofile'),
        ),
    ]
