# Generated by Django 4.2 on 2026-08-26 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_scraperrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groq_tokens_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='groq_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
