# Generated by Django 5.0.2 on 2026-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_profile_groq_tokens_reset_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ownership', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('courses_offered', models.PositiveIntegerField(default=0, help_text='Number of courses offered.')),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('established', models.PositiveIntegerField(blank=True, help_text='Year the college was established.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
