# Generated by Django 5.0.2 on 2026-09-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_seed_jobspy_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspyscraperun',
            name='removed_old',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
