# Generated by Django 5.0.2 on 2026-08-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collaborators',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='goodies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prize_pool_paise',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
