# Generated by Django 5.0.2 on 2026-08-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_map_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
