# Generated by Django 5.0.2 on 2026-08-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_location_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
