# Generated by Django 5.0.2 on 2026-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
