# Generated by Django 5.0.2 on 2026-09-27 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_logo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_is_admin', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('posting_updated', 'Posting edited'), ('posting_status_changed', 'Posting status changed'), ('posting_deleted', 'Posting deleted'), ('profile_updated', 'Company profile edited'), ('kyc_reviewed', 'KYC reviewed'), ('kyc_document_deleted', 'KYC document removed'), ('member_role_changed', 'Teammate role changed'), ('member_updated', 'Teammate details edited'), ('member_removed', 'Teammate removed'), ('employer_deleted', 'Employer deleted')], db_index=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_activity', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='employers.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
