# Generated by Django 5.0.2 on 2026-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='external_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='last_external_click_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='via_external_link',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='apply_mode',
            field=models.CharField(choices=[('kaamlee', 'Apply on Kaamlee'), ('external', 'External apply link')], default='kaamlee', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='external_apply_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
