# Generated by Django 5.0.2 on 2026-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.CharField(choices=[('monthly', '1 Month'), ('quarterly', '3 Months')], default='quarterly', max_length=20),
        ),
    ]
