# Generated by Django 5.0.2 on 2026-08-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=255)),
                ('college_city', models.CharField(blank=True, max_length=100)),
                ('college_state', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('degree_level', models.CharField(choices=[('undergrad', 'Undergraduate'), ('postgrad', 'Postgraduate')], default='undergrad', max_length=10)),
                ('graduation_year', models.PositiveIntegerField()),
                ('id_card_image', models.ImageField(upload_to='ambassador_id_cards/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
